// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"sync"

	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchJobEvent struct {
	GetJobNameStub        func() string
	getJobNameMutex       sync.RWMutex
	getJobNameArgsForCall []struct {
	}
	getJobNameReturns struct {
		result1 string
	}
	getJobNameReturnsOnCall map[int]struct {
		result1 string
	}
	GetJobUidStub        func() string
	getJobUidMutex       sync.RWMutex
	getJobUidArgsForCall []struct {
	}
	getJobUidReturns struct {
		result1 string
	}
	getJobUidReturnsOnCall map[int]struct {
		result1 string
	}
	ParseJobNameStub        func() (batchv1.ParsedJobName, error)
	parseJobNameMutex       sync.RWMutex
	parseJobNameArgsForCall []struct {
	}
	parseJobNameReturns struct {
		result1 batchv1.ParsedJobName
		result2 error
	}
	parseJobNameReturnsOnCall map[int]struct {
		result1 batchv1.ParsedJobName
		result2 error
	}
	SetJobNameStub        func(string)
	setJobNameMutex       sync.RWMutex
	setJobNameArgsForCall []struct {
		arg1 string
	}
	SetJobUidStub        func(string)
	setJobUidMutex       sync.RWMutex
	setJobUidArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchJobEvent) GetJobName() string {
	fake.getJobNameMutex.Lock()
	ret, specificReturn := fake.getJobNameReturnsOnCall[len(fake.getJobNameArgsForCall)]
	fake.getJobNameArgsForCall = append(fake.getJobNameArgsForCall, struct {
	}{})
	stub := fake.GetJobNameStub
	fakeReturns := fake.getJobNameReturns
	fake.recordInvocation("GetJobName", []interface{}{})
	fake.getJobNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchJobEvent) GetJobNameCallCount() int {
	fake.getJobNameMutex.RLock()
	defer fake.getJobNameMutex.RUnlock()
	return len(fake.getJobNameArgsForCall)
}

func (fake *FakeBatchJobEvent) GetJobNameCalls(stub func() string) {
	fake.getJobNameMutex.Lock()
	defer fake.getJobNameMutex.Unlock()
	fake.GetJobNameStub = stub
}

func (fake *FakeBatchJobEvent) GetJobNameReturns(result1 string) {
	fake.getJobNameMutex.Lock()
	defer fake.getJobNameMutex.Unlock()
	fake.GetJobNameStub = nil
	fake.getJobNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBatchJobEvent) GetJobNameReturnsOnCall(i int, result1 string) {
	fake.getJobNameMutex.Lock()
	defer fake.getJobNameMutex.Unlock()
	fake.GetJobNameStub = nil
	if fake.getJobNameReturnsOnCall == nil {
		fake.getJobNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getJobNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBatchJobEvent) GetJobUid() string {
	fake.getJobUidMutex.Lock()
	ret, specificReturn := fake.getJobUidReturnsOnCall[len(fake.getJobUidArgsForCall)]
	fake.getJobUidArgsForCall = append(fake.getJobUidArgsForCall, struct {
	}{})
	stub := fake.GetJobUidStub
	fakeReturns := fake.getJobUidReturns
	fake.recordInvocation("GetJobUid", []interface{}{})
	fake.getJobUidMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchJobEvent) GetJobUidCallCount() int {
	fake.getJobUidMutex.RLock()
	defer fake.getJobUidMutex.RUnlock()
	return len(fake.getJobUidArgsForCall)
}

func (fake *FakeBatchJobEvent) GetJobUidCalls(stub func() string) {
	fake.getJobUidMutex.Lock()
	defer fake.getJobUidMutex.Unlock()
	fake.GetJobUidStub = stub
}

func (fake *FakeBatchJobEvent) GetJobUidReturns(result1 string) {
	fake.getJobUidMutex.Lock()
	defer fake.getJobUidMutex.Unlock()
	fake.GetJobUidStub = nil
	fake.getJobUidReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBatchJobEvent) GetJobUidReturnsOnCall(i int, result1 string) {
	fake.getJobUidMutex.Lock()
	defer fake.getJobUidMutex.Unlock()
	fake.GetJobUidStub = nil
	if fake.getJobUidReturnsOnCall == nil {
		fake.getJobUidReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getJobUidReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBatchJobEvent) ParseJobName() (batchv1.ParsedJobName, error) {
	fake.parseJobNameMutex.Lock()
	ret, specificReturn := fake.parseJobNameReturnsOnCall[len(fake.parseJobNameArgsForCall)]
	fake.parseJobNameArgsForCall = append(fake.parseJobNameArgsForCall, struct {
	}{})
	stub := fake.ParseJobNameStub
	fakeReturns := fake.parseJobNameReturns
	fake.recordInvocation("ParseJobName", []interface{}{})
	fake.parseJobNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBatchJobEvent) ParseJobNameCallCount() int {
	fake.parseJobNameMutex.RLock()
	defer fake.parseJobNameMutex.RUnlock()
	return len(fake.parseJobNameArgsForCall)
}

func (fake *FakeBatchJobEvent) ParseJobNameCalls(stub func() (batchv1.ParsedJobName, error)) {
	fake.parseJobNameMutex.Lock()
	defer fake.parseJobNameMutex.Unlock()
	fake.ParseJobNameStub = stub
}

func (fake *FakeBatchJobEvent) ParseJobNameReturns(result1 batchv1.ParsedJobName, result2 error) {
	fake.parseJobNameMutex.Lock()
	defer fake.parseJobNameMutex.Unlock()
	fake.ParseJobNameStub = nil
	fake.parseJobNameReturns = struct {
		result1 batchv1.ParsedJobName
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchJobEvent) ParseJobNameReturnsOnCall(i int, result1 batchv1.ParsedJobName, result2 error) {
	fake.parseJobNameMutex.Lock()
	defer fake.parseJobNameMutex.Unlock()
	fake.ParseJobNameStub = nil
	if fake.parseJobNameReturnsOnCall == nil {
		fake.parseJobNameReturnsOnCall = make(map[int]struct {
			result1 batchv1.ParsedJobName
			result2 error
		})
	}
	fake.parseJobNameReturnsOnCall[i] = struct {
		result1 batchv1.ParsedJobName
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchJobEvent) SetJobName(arg1 string) {
	fake.setJobNameMutex.Lock()
	fake.setJobNameArgsForCall = append(fake.setJobNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetJobNameStub
	fake.recordInvocation("SetJobName", []interface{}{arg1})
	fake.setJobNameMutex.Unlock()
	if stub != nil {
		fake.SetJobNameStub(arg1)
	}
}

func (fake *FakeBatchJobEvent) SetJobNameCallCount() int {
	fake.setJobNameMutex.RLock()
	defer fake.setJobNameMutex.RUnlock()
	return len(fake.setJobNameArgsForCall)
}

func (fake *FakeBatchJobEvent) SetJobNameCalls(stub func(string)) {
	fake.setJobNameMutex.Lock()
	defer fake.setJobNameMutex.Unlock()
	fake.SetJobNameStub = stub
}

func (fake *FakeBatchJobEvent) SetJobNameArgsForCall(i int) string {
	fake.setJobNameMutex.RLock()
	defer fake.setJobNameMutex.RUnlock()
	argsForCall := fake.setJobNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchJobEvent) SetJobUid(arg1 string) {
	fake.setJobUidMutex.Lock()
	fake.setJobUidArgsForCall = append(fake.setJobUidArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetJobUidStub
	fake.recordInvocation("SetJobUid", []interface{}{arg1})
	fake.setJobUidMutex.Unlock()
	if stub != nil {
		fake.SetJobUidStub(arg1)
	}
}

func (fake *FakeBatchJobEvent) SetJobUidCallCount() int {
	fake.setJobUidMutex.RLock()
	defer fake.setJobUidMutex.RUnlock()
	return len(fake.setJobUidArgsForCall)
}

func (fake *FakeBatchJobEvent) SetJobUidCalls(stub func(string)) {
	fake.setJobUidMutex.Lock()
	defer fake.setJobUidMutex.Unlock()
	fake.SetJobUidStub = stub
}

func (fake *FakeBatchJobEvent) SetJobUidArgsForCall(i int) string {
	fake.setJobUidMutex.RLock()
	defer fake.setJobUidMutex.RUnlock()
	argsForCall := fake.setJobUidArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchJobEvent) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getJobNameMutex.RLock()
	defer fake.getJobNameMutex.RUnlock()
	fake.getJobUidMutex.RLock()
	defer fake.getJobUidMutex.RUnlock()
	fake.parseJobNameMutex.RLock()
	defer fake.parseJobNameMutex.RUnlock()
	fake.setJobNameMutex.RLock()
	defer fake.setJobNameMutex.RUnlock()
	fake.setJobUidMutex.RLock()
	defer fake.setJobUidMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchJobEvent) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchJobEvent = new(FakeBatchJobEvent)
