// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"context"
	"sync"

	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchJobEventHandler struct {
	HandleBatchJobEventStub        func(context.Context, batchv1.BatchJobEvent) error
	handleBatchJobEventMutex       sync.RWMutex
	handleBatchJobEventArgsForCall []struct {
		arg1 context.Context
		arg2 batchv1.BatchJobEvent
	}
	handleBatchJobEventReturns struct {
		result1 error
	}
	handleBatchJobEventReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEvent(arg1 context.Context, arg2 batchv1.BatchJobEvent) error {
	fake.handleBatchJobEventMutex.Lock()
	ret, specificReturn := fake.handleBatchJobEventReturnsOnCall[len(fake.handleBatchJobEventArgsForCall)]
	fake.handleBatchJobEventArgsForCall = append(fake.handleBatchJobEventArgsForCall, struct {
		arg1 context.Context
		arg2 batchv1.BatchJobEvent
	}{arg1, arg2})
	stub := fake.HandleBatchJobEventStub
	fakeReturns := fake.handleBatchJobEventReturns
	fake.recordInvocation("HandleBatchJobEvent", []interface{}{arg1, arg2})
	fake.handleBatchJobEventMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEventCallCount() int {
	fake.handleBatchJobEventMutex.RLock()
	defer fake.handleBatchJobEventMutex.RUnlock()
	return len(fake.handleBatchJobEventArgsForCall)
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEventCalls(stub func(context.Context, batchv1.BatchJobEvent) error) {
	fake.handleBatchJobEventMutex.Lock()
	defer fake.handleBatchJobEventMutex.Unlock()
	fake.HandleBatchJobEventStub = stub
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEventArgsForCall(i int) (context.Context, batchv1.BatchJobEvent) {
	fake.handleBatchJobEventMutex.RLock()
	defer fake.handleBatchJobEventMutex.RUnlock()
	argsForCall := fake.handleBatchJobEventArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEventReturns(result1 error) {
	fake.handleBatchJobEventMutex.Lock()
	defer fake.handleBatchJobEventMutex.Unlock()
	fake.HandleBatchJobEventStub = nil
	fake.handleBatchJobEventReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchJobEventHandler) HandleBatchJobEventReturnsOnCall(i int, result1 error) {
	fake.handleBatchJobEventMutex.Lock()
	defer fake.handleBatchJobEventMutex.Unlock()
	fake.HandleBatchJobEventStub = nil
	if fake.handleBatchJobEventReturnsOnCall == nil {
		fake.handleBatchJobEventReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handleBatchJobEventReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchJobEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleBatchJobEventMutex.RLock()
	defer fake.handleBatchJobEventMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchJobEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchJobEventHandler = new(FakeBatchJobEventHandler)
