// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"sync"

	"cloud.google.com/go/batch/apiv1/batchpb"
	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchTaskIterator struct {
	NextStub        func() (*batchpb.Task, error)
	nextMutex       sync.RWMutex
	nextArgsForCall []struct {
	}
	nextReturns struct {
		result1 *batchpb.Task
		result2 error
	}
	nextReturnsOnCall map[int]struct {
		result1 *batchpb.Task
		result2 error
	}
	PageInfoStub        func() batchv1.BatchPageInfo
	pageInfoMutex       sync.RWMutex
	pageInfoArgsForCall []struct {
	}
	pageInfoReturns struct {
		result1 batchv1.BatchPageInfo
	}
	pageInfoReturnsOnCall map[int]struct {
		result1 batchv1.BatchPageInfo
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchTaskIterator) Next() (*batchpb.Task, error) {
	fake.nextMutex.Lock()
	ret, specificReturn := fake.nextReturnsOnCall[len(fake.nextArgsForCall)]
	fake.nextArgsForCall = append(fake.nextArgsForCall, struct {
	}{})
	stub := fake.NextStub
	fakeReturns := fake.nextReturns
	fake.recordInvocation("Next", []interface{}{})
	fake.nextMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBatchTaskIterator) NextCallCount() int {
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	return len(fake.nextArgsForCall)
}

func (fake *FakeBatchTaskIterator) NextCalls(stub func() (*batchpb.Task, error)) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = stub
}

func (fake *FakeBatchTaskIterator) NextReturns(result1 *batchpb.Task, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	fake.nextReturns = struct {
		result1 *batchpb.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchTaskIterator) NextReturnsOnCall(i int, result1 *batchpb.Task, result2 error) {
	fake.nextMutex.Lock()
	defer fake.nextMutex.Unlock()
	fake.NextStub = nil
	if fake.nextReturnsOnCall == nil {
		fake.nextReturnsOnCall = make(map[int]struct {
			result1 *batchpb.Task
			result2 error
		})
	}
	fake.nextReturnsOnCall[i] = struct {
		result1 *batchpb.Task
		result2 error
	}{result1, result2}
}

func (fake *FakeBatchTaskIterator) PageInfo() batchv1.BatchPageInfo {
	fake.pageInfoMutex.Lock()
	ret, specificReturn := fake.pageInfoReturnsOnCall[len(fake.pageInfoArgsForCall)]
	fake.pageInfoArgsForCall = append(fake.pageInfoArgsForCall, struct {
	}{})
	stub := fake.PageInfoStub
	fakeReturns := fake.pageInfoReturns
	fake.recordInvocation("PageInfo", []interface{}{})
	fake.pageInfoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchTaskIterator) PageInfoCallCount() int {
	fake.pageInfoMutex.RLock()
	defer fake.pageInfoMutex.RUnlock()
	return len(fake.pageInfoArgsForCall)
}

func (fake *FakeBatchTaskIterator) PageInfoCalls(stub func() batchv1.BatchPageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = stub
}

func (fake *FakeBatchTaskIterator) PageInfoReturns(result1 batchv1.BatchPageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = nil
	fake.pageInfoReturns = struct {
		result1 batchv1.BatchPageInfo
	}{result1}
}

func (fake *FakeBatchTaskIterator) PageInfoReturnsOnCall(i int, result1 batchv1.BatchPageInfo) {
	fake.pageInfoMutex.Lock()
	defer fake.pageInfoMutex.Unlock()
	fake.PageInfoStub = nil
	if fake.pageInfoReturnsOnCall == nil {
		fake.pageInfoReturnsOnCall = make(map[int]struct {
			result1 batchv1.BatchPageInfo
		})
	}
	fake.pageInfoReturnsOnCall[i] = struct {
		result1 batchv1.BatchPageInfo
	}{result1}
}

func (fake *FakeBatchTaskIterator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	fake.pageInfoMutex.RLock()
	defer fake.pageInfoMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchTaskIterator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchTaskIterator = new(FakeBatchTaskIterator)
