// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"context"
	"sync"

	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchTaskEventHandler struct {
	HandleBatchTaskEventStub        func(context.Context, batchv1.BatchTaskEvent) error
	handleBatchTaskEventMutex       sync.RWMutex
	handleBatchTaskEventArgsForCall []struct {
		arg1 context.Context
		arg2 batchv1.BatchTaskEvent
	}
	handleBatchTaskEventReturns struct {
		result1 error
	}
	handleBatchTaskEventReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEvent(arg1 context.Context, arg2 batchv1.BatchTaskEvent) error {
	fake.handleBatchTaskEventMutex.Lock()
	ret, specificReturn := fake.handleBatchTaskEventReturnsOnCall[len(fake.handleBatchTaskEventArgsForCall)]
	fake.handleBatchTaskEventArgsForCall = append(fake.handleBatchTaskEventArgsForCall, struct {
		arg1 context.Context
		arg2 batchv1.BatchTaskEvent
	}{arg1, arg2})
	stub := fake.HandleBatchTaskEventStub
	fakeReturns := fake.handleBatchTaskEventReturns
	fake.recordInvocation("HandleBatchTaskEvent", []interface{}{arg1, arg2})
	fake.handleBatchTaskEventMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEventCallCount() int {
	fake.handleBatchTaskEventMutex.RLock()
	defer fake.handleBatchTaskEventMutex.RUnlock()
	return len(fake.handleBatchTaskEventArgsForCall)
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEventCalls(stub func(context.Context, batchv1.BatchTaskEvent) error) {
	fake.handleBatchTaskEventMutex.Lock()
	defer fake.handleBatchTaskEventMutex.Unlock()
	fake.HandleBatchTaskEventStub = stub
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEventArgsForCall(i int) (context.Context, batchv1.BatchTaskEvent) {
	fake.handleBatchTaskEventMutex.RLock()
	defer fake.handleBatchTaskEventMutex.RUnlock()
	argsForCall := fake.handleBatchTaskEventArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEventReturns(result1 error) {
	fake.handleBatchTaskEventMutex.Lock()
	defer fake.handleBatchTaskEventMutex.Unlock()
	fake.HandleBatchTaskEventStub = nil
	fake.handleBatchTaskEventReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchTaskEventHandler) HandleBatchTaskEventReturnsOnCall(i int, result1 error) {
	fake.handleBatchTaskEventMutex.Lock()
	defer fake.handleBatchTaskEventMutex.Unlock()
	fake.HandleBatchTaskEventStub = nil
	if fake.handleBatchTaskEventReturnsOnCall == nil {
		fake.handleBatchTaskEventReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.handleBatchTaskEventReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBatchTaskEventHandler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.handleBatchTaskEventMutex.RLock()
	defer fake.handleBatchTaskEventMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchTaskEventHandler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchTaskEventHandler = new(FakeBatchTaskEventHandler)
