// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"sync"

	"cloud.google.com/go/batch/apiv1/batchpb"
	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchTaskEvent struct {
	GetTaskStub        func() *batchpb.Task
	getTaskMutex       sync.RWMutex
	getTaskArgsForCall []struct {
	}
	getTaskReturns struct {
		result1 *batchpb.Task
	}
	getTaskReturnsOnCall map[int]struct {
		result1 *batchpb.Task
	}
	SetTaskStub        func(*batchpb.Task)
	setTaskMutex       sync.RWMutex
	setTaskArgsForCall []struct {
		arg1 *batchpb.Task
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchTaskEvent) GetTask() *batchpb.Task {
	fake.getTaskMutex.Lock()
	ret, specificReturn := fake.getTaskReturnsOnCall[len(fake.getTaskArgsForCall)]
	fake.getTaskArgsForCall = append(fake.getTaskArgsForCall, struct {
	}{})
	stub := fake.GetTaskStub
	fakeReturns := fake.getTaskReturns
	fake.recordInvocation("GetTask", []interface{}{})
	fake.getTaskMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchTaskEvent) GetTaskCallCount() int {
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	return len(fake.getTaskArgsForCall)
}

func (fake *FakeBatchTaskEvent) GetTaskCalls(stub func() *batchpb.Task) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = stub
}

func (fake *FakeBatchTaskEvent) GetTaskReturns(result1 *batchpb.Task) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = nil
	fake.getTaskReturns = struct {
		result1 *batchpb.Task
	}{result1}
}

func (fake *FakeBatchTaskEvent) GetTaskReturnsOnCall(i int, result1 *batchpb.Task) {
	fake.getTaskMutex.Lock()
	defer fake.getTaskMutex.Unlock()
	fake.GetTaskStub = nil
	if fake.getTaskReturnsOnCall == nil {
		fake.getTaskReturnsOnCall = make(map[int]struct {
			result1 *batchpb.Task
		})
	}
	fake.getTaskReturnsOnCall[i] = struct {
		result1 *batchpb.Task
	}{result1}
}

func (fake *FakeBatchTaskEvent) SetTask(arg1 *batchpb.Task) {
	fake.setTaskMutex.Lock()
	fake.setTaskArgsForCall = append(fake.setTaskArgsForCall, struct {
		arg1 *batchpb.Task
	}{arg1})
	stub := fake.SetTaskStub
	fake.recordInvocation("SetTask", []interface{}{arg1})
	fake.setTaskMutex.Unlock()
	if stub != nil {
		fake.SetTaskStub(arg1)
	}
}

func (fake *FakeBatchTaskEvent) SetTaskCallCount() int {
	fake.setTaskMutex.RLock()
	defer fake.setTaskMutex.RUnlock()
	return len(fake.setTaskArgsForCall)
}

func (fake *FakeBatchTaskEvent) SetTaskCalls(stub func(*batchpb.Task)) {
	fake.setTaskMutex.Lock()
	defer fake.setTaskMutex.Unlock()
	fake.SetTaskStub = stub
}

func (fake *FakeBatchTaskEvent) SetTaskArgsForCall(i int) *batchpb.Task {
	fake.setTaskMutex.RLock()
	defer fake.setTaskMutex.RUnlock()
	argsForCall := fake.setTaskArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchTaskEvent) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getTaskMutex.RLock()
	defer fake.getTaskMutex.RUnlock()
	fake.setTaskMutex.RLock()
	defer fake.setTaskMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchTaskEvent) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchTaskEvent = new(FakeBatchTaskEvent)
