// Code generated by counterfeiter. DO NOT EDIT.
package batchv1fake

import (
	"sync"

	"cloud.google.com/go/batch/apiv1/batchpb"
	batchv1 "github.com/connect-sdk/batch-api/proto/connect/batch/v1"
)

type FakeBatchJobEvent struct {
	GetJobStub        func() *batchpb.Job
	getJobMutex       sync.RWMutex
	getJobArgsForCall []struct {
	}
	getJobReturns struct {
		result1 *batchpb.Job
	}
	getJobReturnsOnCall map[int]struct {
		result1 *batchpb.Job
	}
	SetJobStub        func(*batchpb.Job)
	setJobMutex       sync.RWMutex
	setJobArgsForCall []struct {
		arg1 *batchpb.Job
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchJobEvent) GetJob() *batchpb.Job {
	fake.getJobMutex.Lock()
	ret, specificReturn := fake.getJobReturnsOnCall[len(fake.getJobArgsForCall)]
	fake.getJobArgsForCall = append(fake.getJobArgsForCall, struct {
	}{})
	stub := fake.GetJobStub
	fakeReturns := fake.getJobReturns
	fake.recordInvocation("GetJob", []interface{}{})
	fake.getJobMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchJobEvent) GetJobCallCount() int {
	fake.getJobMutex.RLock()
	defer fake.getJobMutex.RUnlock()
	return len(fake.getJobArgsForCall)
}

func (fake *FakeBatchJobEvent) GetJobCalls(stub func() *batchpb.Job) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = stub
}

func (fake *FakeBatchJobEvent) GetJobReturns(result1 *batchpb.Job) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = nil
	fake.getJobReturns = struct {
		result1 *batchpb.Job
	}{result1}
}

func (fake *FakeBatchJobEvent) GetJobReturnsOnCall(i int, result1 *batchpb.Job) {
	fake.getJobMutex.Lock()
	defer fake.getJobMutex.Unlock()
	fake.GetJobStub = nil
	if fake.getJobReturnsOnCall == nil {
		fake.getJobReturnsOnCall = make(map[int]struct {
			result1 *batchpb.Job
		})
	}
	fake.getJobReturnsOnCall[i] = struct {
		result1 *batchpb.Job
	}{result1}
}

func (fake *FakeBatchJobEvent) SetJob(arg1 *batchpb.Job) {
	fake.setJobMutex.Lock()
	fake.setJobArgsForCall = append(fake.setJobArgsForCall, struct {
		arg1 *batchpb.Job
	}{arg1})
	stub := fake.SetJobStub
	fake.recordInvocation("SetJob", []interface{}{arg1})
	fake.setJobMutex.Unlock()
	if stub != nil {
		fake.SetJobStub(arg1)
	}
}

func (fake *FakeBatchJobEvent) SetJobCallCount() int {
	fake.setJobMutex.RLock()
	defer fake.setJobMutex.RUnlock()
	return len(fake.setJobArgsForCall)
}

func (fake *FakeBatchJobEvent) SetJobCalls(stub func(*batchpb.Job)) {
	fake.setJobMutex.Lock()
	defer fake.setJobMutex.Unlock()
	fake.SetJobStub = stub
}

func (fake *FakeBatchJobEvent) SetJobArgsForCall(i int) *batchpb.Job {
	fake.setJobMutex.RLock()
	defer fake.setJobMutex.RUnlock()
	argsForCall := fake.setJobArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchJobEvent) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getJobMutex.RLock()
	defer fake.getJobMutex.RUnlock()
	fake.setJobMutex.RLock()
	defer fake.setJobMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchJobEvent) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batchv1.BatchJobEvent = new(FakeBatchJobEvent)
