// Code generated by protoc-gen-go-resource. DO NOT EDIT.
package batchv1

import (
	"fmt"
	"strings"
)

type ParsedProjectName struct {
	ProjectID string
}

func ParseProjectName(s string) (ParsedProjectName, error) {
	p := strings.Split(s, "/")
	if len(p) != 2 {
		return ParsedProjectName{}, fmt.Errorf("parse %q: bad number of segments, want: 2, got: %d", s, len(p))
	}

	var out ParsedProjectName

	if p[0] != "projects" {
		return ParsedProjectName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	return out, nil
}

func ParseFullProjectName(s string) (ParsedProjectName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedProjectName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseProjectName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedProjectName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	return out
}

func (n ParsedProjectName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedNetworkName struct {
	ProjectID string

	NetworkID string
}

func ParseNetworkName(s string) (ParsedNetworkName, error) {
	p := strings.Split(s, "/")
	if len(p) != 5 {
		return ParsedNetworkName{}, fmt.Errorf("parse %q: bad number of segments, want: 5, got: %d", s, len(p))
	}

	var out ParsedNetworkName

	if p[0] != "projects" {
		return ParsedNetworkName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "global" {
		return ParsedNetworkName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "global", p[2])
	}

	if p[3] != "networks" {
		return ParsedNetworkName{}, fmt.Errorf("parse %q: bad segment 3, want: %q, got: %q", s, "networks", p[3])
	}

	out.NetworkID = p[4]

	return out, nil
}

func ParseFullNetworkName(s string) (ParsedNetworkName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedNetworkName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseNetworkName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedNetworkName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "global"

	out += "/"

	out += "networks"

	out += "/"

	out += n.NetworkID

	return out
}

func (n ParsedNetworkName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedSubnetworkName struct {
	ProjectID string

	RegionID string

	SubnetworkID string
}

func ParseSubnetworkName(s string) (ParsedSubnetworkName, error) {
	p := strings.Split(s, "/")
	if len(p) != 6 {
		return ParsedSubnetworkName{}, fmt.Errorf("parse %q: bad number of segments, want: 6, got: %d", s, len(p))
	}

	var out ParsedSubnetworkName

	if p[0] != "projects" {
		return ParsedSubnetworkName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "regions" {
		return ParsedSubnetworkName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "regions", p[2])
	}

	out.RegionID = p[3]

	if p[4] != "subnetworks" {
		return ParsedSubnetworkName{}, fmt.Errorf("parse %q: bad segment 4, want: %q, got: %q", s, "subnetworks", p[4])
	}

	out.SubnetworkID = p[5]

	return out, nil
}

func ParseFullSubnetworkName(s string) (ParsedSubnetworkName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedSubnetworkName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseSubnetworkName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedSubnetworkName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "regions"

	out += "/"

	out += n.RegionID

	out += "/"

	out += "subnetworks"

	out += "/"

	out += n.SubnetworkID

	return out
}

func (n ParsedSubnetworkName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedRegionName struct {
	ProjectID string

	RegionID string
}

func ParseRegionName(s string) (ParsedRegionName, error) {
	p := strings.Split(s, "/")
	if len(p) != 4 {
		return ParsedRegionName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(p))
	}

	var out ParsedRegionName

	if p[0] != "projects" {
		return ParsedRegionName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "regions" {
		return ParsedRegionName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "regions", p[2])
	}

	out.RegionID = p[3]

	return out, nil
}

func ParseFullRegionName(s string) (ParsedRegionName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedRegionName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseRegionName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedRegionName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "regions"

	out += "/"

	out += n.RegionID

	return out
}

func (n ParsedRegionName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedLocationName struct {
	ProjectID string

	LocationID string
}

func ParseLocationName(s string) (ParsedLocationName, error) {
	p := strings.Split(s, "/")
	if len(p) != 4 {
		return ParsedLocationName{}, fmt.Errorf("parse %q: bad number of segments, want: 4, got: %d", s, len(p))
	}

	var out ParsedLocationName

	if p[0] != "projects" {
		return ParsedLocationName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "locations" {
		return ParsedLocationName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "locations", p[2])
	}

	out.LocationID = p[3]

	return out, nil
}

func ParseFullLocationName(s string) (ParsedLocationName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedLocationName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseLocationName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedLocationName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "locations"

	out += "/"

	out += n.LocationID

	return out
}

func (n ParsedLocationName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedJobName struct {
	ProjectID string

	LocationID string

	JobID string
}

func ParseJobName(s string) (ParsedJobName, error) {
	p := strings.Split(s, "/")
	if len(p) != 6 {
		return ParsedJobName{}, fmt.Errorf("parse %q: bad number of segments, want: 6, got: %d", s, len(p))
	}

	var out ParsedJobName

	if p[0] != "projects" {
		return ParsedJobName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "locations" {
		return ParsedJobName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "locations", p[2])
	}

	out.LocationID = p[3]

	if p[4] != "jobs" {
		return ParsedJobName{}, fmt.Errorf("parse %q: bad segment 4, want: %q, got: %q", s, "jobs", p[4])
	}

	out.JobID = p[5]

	return out, nil
}

func ParseFullJobName(s string) (ParsedJobName, error) {
	if !strings.HasPrefix(s, "//batch.googleapis.com/") {
		return ParsedJobName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.googleapis.com/")
	}

	return ParseJobName(strings.TrimPrefix(s, "//batch.googleapis.com/"))
}

func (n ParsedJobName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "locations"

	out += "/"

	out += n.LocationID

	out += "/"

	out += "jobs"

	out += "/"

	out += n.JobID

	return out
}

func (n ParsedJobName) FullName() string {
	return "//batch.googleapis.com/" + n.Name()
}

type ParsedTaskGroupName struct {
	ProjectID string

	LocationID string

	JobID string

	TaskGroupID string
}

func ParseTaskGroupName(s string) (ParsedTaskGroupName, error) {
	p := strings.Split(s, "/")
	if len(p) != 8 {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: bad number of segments, want: 8, got: %d", s, len(p))
	}

	var out ParsedTaskGroupName

	if p[0] != "projects" {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "locations" {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "locations", p[2])
	}

	out.LocationID = p[3]

	if p[4] != "jobs" {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: bad segment 4, want: %q, got: %q", s, "jobs", p[4])
	}

	out.JobID = p[5]

	if p[6] != "taskGroups" {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: bad segment 6, want: %q, got: %q", s, "taskGroups", p[6])
	}

	out.TaskGroupID = p[7]

	return out, nil
}

func ParseFullTaskGroupName(s string) (ParsedTaskGroupName, error) {
	if !strings.HasPrefix(s, "//batch.google.com/") {
		return ParsedTaskGroupName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.google.com/")
	}

	return ParseTaskGroupName(strings.TrimPrefix(s, "//batch.google.com/"))
}

func (n ParsedTaskGroupName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "locations"

	out += "/"

	out += n.LocationID

	out += "/"

	out += "jobs"

	out += "/"

	out += n.JobID

	out += "/"

	out += "taskGroups"

	out += "/"

	out += n.TaskGroupID

	return out
}

func (n ParsedTaskGroupName) FullName() string {
	return "//batch.google.com/" + n.Name()
}

type ParsedTaskName struct {
	ProjectID string

	LocationID string

	JobID string

	TaskGroupID string

	TaskID string
}

func ParseTaskName(s string) (ParsedTaskName, error) {
	p := strings.Split(s, "/")
	if len(p) != 10 {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad number of segments, want: 10, got: %d", s, len(p))
	}

	var out ParsedTaskName

	if p[0] != "projects" {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad segment 0, want: %q, got: %q", s, "projects", p[0])
	}

	out.ProjectID = p[1]

	if p[2] != "locations" {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad segment 2, want: %q, got: %q", s, "locations", p[2])
	}

	out.LocationID = p[3]

	if p[4] != "jobs" {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad segment 4, want: %q, got: %q", s, "jobs", p[4])
	}

	out.JobID = p[5]

	if p[6] != "taskGroups" {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad segment 6, want: %q, got: %q", s, "taskGroups", p[6])
	}

	out.TaskGroupID = p[7]

	if p[8] != "tasks" {
		return ParsedTaskName{}, fmt.Errorf("parse %q: bad segment 8, want: %q, got: %q", s, "tasks", p[8])
	}

	out.TaskID = p[9]

	return out, nil
}

func ParseFullTaskName(s string) (ParsedTaskName, error) {
	if !strings.HasPrefix(s, "//batch.googleapis.com/") {
		return ParsedTaskName{}, fmt.Errorf("parse %q: invalid prefix, want: %q", s, "//batch.googleapis.com/")
	}

	return ParseTaskName(strings.TrimPrefix(s, "//batch.googleapis.com/"))
}

func (n ParsedTaskName) Name() string {
	var out string

	out += "projects"

	out += "/"

	out += n.ProjectID

	out += "/"

	out += "locations"

	out += "/"

	out += n.LocationID

	out += "/"

	out += "jobs"

	out += "/"

	out += n.JobID

	out += "/"

	out += "taskGroups"

	out += "/"

	out += n.TaskGroupID

	out += "/"

	out += "tasks"

	out += "/"

	out += n.TaskID

	return out
}

func (n ParsedTaskName) FullName() string {
	return "//batch.googleapis.com/" + n.Name()
}

func (x *BatchJobStateChangedEvent) ParseJobName() (ParsedJobName, error) {
	return ParseJobName(x.JobName)
}

func (x *BatchTaskStateChangedEvent) ParseTaskName() (ParsedTaskName, error) {
	return ParseTaskName(x.TaskName)
}
