// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: connect/batch/v1/batch.proto

package batchv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BatchJobStateChangedEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchJobStateChangedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchJobStateChangedEvent with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchJobStateChangedEventMultiError, or nil if none found.
func (m *BatchJobStateChangedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchJobStateChangedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for JobName

	// no validation rules for JobUid

	// no validation rules for OldJobState

	// no validation rules for NewJobState

	if len(errors) > 0 {
		return BatchJobStateChangedEventMultiError(errors)
	}

	return nil
}

// BatchJobStateChangedEventMultiError is an error wrapping multiple validation
// errors returned by BatchJobStateChangedEvent.ValidateAll() if the
// designated constraints aren't met.
type BatchJobStateChangedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchJobStateChangedEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchJobStateChangedEventMultiError) AllErrors() []error { return m }

// BatchJobStateChangedEventValidationError is the validation error returned by
// BatchJobStateChangedEvent.Validate if the designated constraints aren't met.
type BatchJobStateChangedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchJobStateChangedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchJobStateChangedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchJobStateChangedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchJobStateChangedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchJobStateChangedEventValidationError) ErrorName() string {
	return "BatchJobStateChangedEventValidationError"
}

// Error satisfies the builtin error interface
func (e BatchJobStateChangedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchJobStateChangedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchJobStateChangedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchJobStateChangedEventValidationError{}

// Validate checks the field values on BatchTaskStateChangedEvent with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchTaskStateChangedEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchTaskStateChangedEvent with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchTaskStateChangedEventMultiError, or nil if none found.
func (m *BatchTaskStateChangedEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchTaskStateChangedEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskName

	// no validation rules for OldTaskState

	// no validation rules for NewTaskState

	if len(errors) > 0 {
		return BatchTaskStateChangedEventMultiError(errors)
	}

	return nil
}

// BatchTaskStateChangedEventMultiError is an error wrapping multiple
// validation errors returned by BatchTaskStateChangedEvent.ValidateAll() if
// the designated constraints aren't met.
type BatchTaskStateChangedEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchTaskStateChangedEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchTaskStateChangedEventMultiError) AllErrors() []error { return m }

// BatchTaskStateChangedEventValidationError is the validation error returned
// by BatchTaskStateChangedEvent.Validate if the designated constraints aren't met.
type BatchTaskStateChangedEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchTaskStateChangedEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchTaskStateChangedEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchTaskStateChangedEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchTaskStateChangedEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchTaskStateChangedEventValidationError) ErrorName() string {
	return "BatchTaskStateChangedEventValidationError"
}

// Error satisfies the builtin error interface
func (e BatchTaskStateChangedEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchTaskStateChangedEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchTaskStateChangedEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchTaskStateChangedEventValidationError{}
